services:
  backend:
    build: ./backend
    container_name: clarity-backend
    ports:
      - "7860:7860"

  frontend:
    build: ./frontend
    container_name: clarity-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
